#!/bin/bash
# Fix HTTP Router Label - Direkt im Project Directory
# Überschreibt fehlerhaften HTTP Router Label mit korrektem

set -e

echo "🔧 FIX HTTP ROUTER LABEL"
echo "========================"
echo ""

# 1. Finde Backend Container
BACKEND_CONTAINER=$(docker ps -a | grep backend | grep mw0ck04s8go048c0g4so48cc | awk '{print $1}' | head -1)
if [ -z "$BACKEND_CONTAINER" ]; then
    echo "❌ Backend Container nicht gefunden!"
    exit 1
fi

echo "✅ Backend Container: $BACKEND_CONTAINER"

# 2. Finde Project Directory
PROJECT_DIR=$(docker inspect $BACKEND_CONTAINER | jq -r '.[0].Config.Labels["com.docker.compose.project.working_dir"]')
if [ -z "$PROJECT_DIR" ] || [ "$PROJECT_DIR" = "null" ]; then
    echo "❌ Project Directory nicht gefunden!"
    exit 1
fi

echo "✅ Project Directory: $PROJECT_DIR"
echo ""

# 3. Erstelle docker-compose.override.yml mit korrigierten Labels
echo "📝 Erstelle docker-compose.override.yml..."

cat > "$PROJECT_DIR/docker-compose.override.yml" <<'EOF'
# Coolify Label Override - Fix HTTP Router
# Generated by fix-http-router-label.sh

services:
  backend:
    labels:
      # Überschreibe fehlerhaften HTTP Router mit korrektem
      traefik.http.routers.http-0-mw0ck04s8go048c0g4so48cc-backend.rule: "Host(`dev.brain.falklabs.de`)"

      # Optional: Entferne Stripprefix Middleware (falls nicht benötigt)
      # traefik.http.middlewares.http-0-mw0ck04s8go048c0g4so48cc-backend-stripprefix.stripprefix.prefixes: ""

      # HTTPS Router bleibt unverändert (ist korrekt)
EOF

echo "✅ Override erstellt: $PROJECT_DIR/docker-compose.override.yml"
echo ""

# 4. Zeige Override
echo "📋 Override Inhalt:"
cat "$PROJECT_DIR/docker-compose.override.yml"
echo ""

# 5. Restart mit Override
echo "🔄 Restart Backend mit Override..."
cd "$PROJECT_DIR"

# Check ob docker-compose.yml existiert
if [ ! -f "docker-compose.yml" ]; then
    echo "❌ docker-compose.yml nicht gefunden in $PROJECT_DIR"
    echo "📂 Verzeichnis-Inhalt:"
    ls -la
    exit 1
fi

# Stoppe Backend
echo "   Stoppe Backend..."
docker-compose stop backend 2>/dev/null || docker compose stop backend

# Entferne Container
echo "   Entferne alten Container..."
docker-compose rm -f backend 2>/dev/null || docker compose rm -f backend

# Starte mit Override neu
echo "   Starte Backend mit Override..."
docker-compose up -d backend 2>/dev/null || docker compose up -d backend

echo "✅ Backend neu gestartet mit Override"
echo ""

# 6. Warte auf Start
echo "⏳ Warte 20 Sekunden..."
sleep 20

# 7. Check neue Labels
NEW_BACKEND=$(docker ps | grep backend | grep mw0ck04s8go048c0g4so48cc | awk '{print $1}' | head -1)
if [ -z "$NEW_BACKEND" ]; then
    echo "⚠️  Backend Container nicht gefunden (noch am starten?)"
    sleep 10
    NEW_BACKEND=$(docker ps | grep backend | grep mw0ck04s8go048c0g4so48cc | awk '{print $1}' | head -1)
fi

if [ -n "$NEW_BACKEND" ]; then
    echo "🏷️  Neue HTTP Router Label:"
    docker inspect $NEW_BACKEND | grep "http-0-mw0ck04s8go048c0g4so48cc-backend.rule" || echo "   Label nicht gefunden (evtl. erfolgreich entfernt?)"
fi
echo ""

# 8. Validation
echo "========================"
echo "🧪 VALIDATION"
echo "========================"
echo ""

echo "1️⃣ Traefik Logs (letzte 5 Zeilen mit 'Host')..."
docker logs $(docker ps | grep traefik | awk '{print $1}') 2>&1 | grep -i "host" | tail -5 || echo "   Keine Host-Errors gefunden ✅"
echo ""

echo "2️⃣ Backend Health Check..."
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://dev.brain.falklabs.de/api/health)
if [ "$HTTP_STATUS" = "200" ]; then
    echo "   ✅ Backend antwortet: HTTP $HTTP_STATUS"
    echo ""
    curl -I https://dev.brain.falklabs.de/api/health
else
    echo "   ⚠️  Backend HTTP Status: $HTTP_STATUS"
    echo "   Warte weitere 10 Sekunden..."
    sleep 10
    HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://dev.brain.falklabs.de/api/health)
    echo "   Neuer Status: $HTTP_STATUS"
fi

echo ""
echo "========================"
echo "✅ FIX ABGESCHLOSSEN"
echo "========================"
echo ""
echo "📊 Nächste Schritte wenn es nicht funktioniert:"
echo "1. Check Traefik Logs: docker logs coolify-proxy 2>&1 | grep -i 'empty args'"
echo "2. Check Backend Logs: docker logs $NEW_BACKEND 2>&1 | tail -20"
echo "3. Override anpassen: nano $PROJECT_DIR/docker-compose.override.yml"
echo "4. Erneuter Restart: cd $PROJECT_DIR && docker-compose restart backend"
