#!/bin/bash
# ControlDeck v2 Deployment Guide

echo "=== ControlDeck v2 Deployment ==="
echo ""
echo "Service: controldeck-v2"
echo "Domain: control.brain.falklabs.de (v2 subdomain empfohlen: control-v2.brain.falklabs.de)"
echo "Port: 3000"
echo ""
echo "Schritt-für-Schritt Deployment:"
echo ""
echo "1. Öffne Coolify UI: http://46.224.37.114:8000"
echo ""
echo "2. Wähle Projekt: BRAiN"
echo ""
echo "3. Klicke: + Add Service → Docker Compose"
echo ""
echo "4. Konfiguration:"
echo "   Name: controldeck-v2"
echo "   Description: BRAiN ControlDeck v2 - Enterprise Dashboard"
echo "   Domain: control-v2.brain.falklabs.de (oder control.brain.falklabs.de wenn altes gelöscht)"
echo "   Port: 3000"
echo ""
echo "5. Docker Compose einfügen:"
cat /home/oli/projects/BRAiN/BRAiN/frontend/controldeck-v2/docker-compose.yml
echo ""
echo "6. Environment Variables:"
echo "   PORT=3000"
echo "   NODE_ENV=production"
echo "   NEXT_PUBLIC_BRAIN_API_BASE=http://backend:8000"
echo ""
echo "7. Source: Local Directory"
echo "   Path: /home/oli/projects/BRAiN/BRAiN/frontend/controldeck-v2"
echo ""
echo "8. Klicke: Deploy"
echo ""
echo "Hinweis: Der erste Build dauert 5-10 Minuten (npm install + build)"
