"""Built-in Agent Blueprints."""

from .fleet_coordinator import FLEET_COORDINATOR_BLUEPRINT
from .safety_monitor import SAFETY_MONITOR_BLUEPRINT
from .navigation_planner import NAVIGATION_PLANNER_BLUEPRINT
from .code_specialist import CODE_SPECIALIST_BLUEPRINT
from .ops_specialist import OPS_SPECIALIST_BLUEPRINT

ALL_BUILTIN_BLUEPRINTS = [
    FLEET_COORDINATOR_BLUEPRINT,
    SAFETY_MONITOR_BLUEPRINT,
    NAVIGATION_PLANNER_BLUEPRINT,
    CODE_SPECIALIST_BLUEPRINT,
    OPS_SPECIALIST_BLUEPRINT,
]

__all__ = [
    "FLEET_COORDINATOR_BLUEPRINT",
    "SAFETY_MONITOR_BLUEPRINT",
    "NAVIGATION_PLANNER_BLUEPRINT",
    "CODE_SPECIALIST_BLUEPRINT",
    "OPS_SPECIALIST_BLUEPRINT",
    "ALL_BUILTIN_BLUEPRINTS",
]
