"""Add auth audit log and policies tables

Revision ID: 016_auth_governance_tables
Revises: 015_add_audit_logging
Create Date: 2025-02-25 12:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '016_auth_governance_tables'
down_revision: Union[str, None] = '015_add_audit_logging'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create auth_audit_log table
    op.create_table(
        'auth_audit_log',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('principal_id', sa.String(length=255), nullable=False),
        sa.Column('principal_type', sa.String(length=50), nullable=False),
        sa.Column('action', sa.String(length=255), nullable=False),
        sa.Column('resource_id', sa.String(length=255), nullable=True),
        sa.Column('decision', sa.String(length=50), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('policy_matched', sa.String(length=255), nullable=True),
        sa.Column('rule_matched', sa.String(length=255), nullable=True),
        sa.Column('risk_tier', sa.String(length=50), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('request_id', sa.String(length=255), nullable=True),
        sa.Column('session_id', sa.String(length=255), nullable=True),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('agent_id', sa.String(length=255), nullable=True),
        sa.Column('organization_id', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for auth_audit_log
    op.create_index('idx_auth_audit_timestamp', 'auth_audit_log', ['timestamp'])
    op.create_index('idx_auth_audit_principal', 'auth_audit_log', ['principal_id'])
    op.create_index('idx_auth_audit_action', 'auth_audit_log', ['action'])
    op.create_index('idx_auth_audit_decision', 'auth_audit_log', ['decision'])
    op.create_index('idx_auth_audit_resource', 'auth_audit_log', ['resource_id'])
    op.create_index('idx_auth_audit_policy', 'auth_audit_log', ['policy_matched'])
    op.create_index('idx_auth_audit_request', 'auth_audit_log', ['request_id'])
    op.create_index('idx_auth_audit_session', 'auth_audit_log', ['session_id'])
    op.create_index('idx_auth_audit_agent', 'auth_audit_log', ['agent_id'])
    op.create_index('idx_auth_audit_org', 'auth_audit_log', ['organization_id'])
    
    # Create policies table
    op.create_table(
        'policies',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('display_name', sa.String(length=255), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('version', sa.String(length=50), nullable=False),
        sa.Column('resource_pattern', sa.String(length=500), nullable=False),
        sa.Column('action_pattern', sa.String(length=500), nullable=False),
        sa.Column('effect', sa.String(length=50), nullable=False),
        sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_system', sa.Boolean(), nullable=False),
        sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL')
    )
    
    # Create indexes for policies
    op.create_index('idx_policies_name', 'policies', ['name'], unique=True)
    op.create_index('idx_policies_priority', 'policies', ['priority'])
    op.create_index('idx_policies_active', 'policies', ['is_active'])
    op.create_index('idx_policies_deleted', 'policies', ['is_deleted'])
    op.create_index('idx_policies_created_by', 'policies', ['created_by'])
    
    # ### end Alembic commands ###
    
    # Insert default policies
    op.execute("""
        INSERT INTO policies (
            id, name, display_name, description, version, 
            resource_pattern, action_pattern, effect, conditions, 
            priority, is_active, is_system, created_at, updated_at, 
            is_deleted, tags, metadata
        ) VALUES (
            gen_random_uuid(),
            'admin_full_access',
            'Admin Full Access',
            'Administrators have unrestricted access to all resources and actions',
            '1.0.0',
            '*',
            '*',
            'allow',
            '[{"field": "agent.role", "operator": "==", "value": "admin"}]'::jsonb,
            1000,
            true,
            true,
            NOW(),
            NOW(),
            false,
            '["system", "admin"]'::jsonb,
            '{"system": true}'::jsonb
        );
    """)
    
    op.execute("""
        INSERT INTO policies (
            id, name, display_name, description, version, 
            resource_pattern, action_pattern, effect, conditions, 
            priority, is_active, is_system, created_at, updated_at, 
            is_deleted, tags, metadata
        ) VALUES (
            gen_random_uuid(),
            'guest_read_only',
            'Guest Read-Only Access',
            'Guests can only read data, no modifications allowed',
            '1.0.0',
            '*',
            '*',
            'deny',
            '[{"field": "agent.role", "operator": "==", "value": "guest"}]'::jsonb,
            50,
            true,
            true,
            NOW(),
            NOW(),
            false,
            '["system", "guest"]'::jsonb,
            '{"system": true, "read_only": true}'::jsonb
        );
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes for policies
    op.drop_index('idx_policies_created_by', table_name='policies')
    op.drop_index('idx_policies_deleted', table_name='policies')
    op.drop_index('idx_policies_active', table_name='policies')
    op.drop_index('idx_policies_priority', table_name='policies')
    op.drop_index('idx_policies_name', table_name='policies')
    
    # Drop policies table
    op.drop_table('policies')
    
    # Drop indexes for auth_audit_log
    op.drop_index('idx_auth_audit_org', table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_agent', table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_session', table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_request', table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_policy', table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_resource', table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_decision', table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_action', table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_principal', table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_timestamp', table_name='auth_audit_log')
    
    # Drop auth_audit_log table
    op.drop_table('auth_audit_log')
    
    # ### end Alembic commands ###
