"""Add token tables - RefreshToken, ServiceAccount, AgentCredential

Revision ID: a1_add_token_tables
Revises: 6b797059f074
Create Date: 2026-02-25 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1_add_token_tables'
down_revision: Union[str, None] = '6b797059f074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create refresh_tokens table
    op.create_table('refresh_tokens',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('token_hash', sa.String(length=255), nullable=False),
        sa.Column('token_family', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.Column('revoked_at', sa.DateTime(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
        sa.Column('previous_token_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('rotation_count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['previous_token_id'], ['refresh_tokens.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_status'), 'refresh_tokens', ['status'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_family'), 'refresh_tokens', ['token_family'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    
    # Create service_accounts table
    op.create_table('service_accounts',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('client_id', sa.String(length=255), nullable=False),
        sa.Column('client_secret_hash', sa.String(length=255), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('scopes', sa.JSON(), nullable=False),
        sa.Column('roles', sa.JSON(), nullable=False),
        sa.Column('allowed_ips', sa.JSON(), nullable=True),
        sa.Column('allowed_origins', sa.JSON(), nullable=True),
        sa.Column('rate_limit', sa.Integer(), nullable=False),
        sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('owner_team', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('last_ip', sa.String(length=45), nullable=True),
        sa.Column('use_count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_accounts_client_id'), 'service_accounts', ['client_id'], unique=True)
    op.create_index(op.f('ix_service_accounts_name'), 'service_accounts', ['name'], unique=True)
    op.create_index(op.f('ix_service_accounts_status'), 'service_accounts', ['status'], unique=False)
    
    # Create agent_credentials table
    op.create_table('agent_credentials',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('agent_id', sa.String(length=255), nullable=False),
        sa.Column('agent_name', sa.String(length=255), nullable=False),
        sa.Column('agent_type', sa.String(length=100), nullable=False),
        sa.Column('credential_hash', sa.String(length=255), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('capabilities', sa.JSON(), nullable=False),
        sa.Column('allowed_scopes', sa.JSON(), nullable=False),
        sa.Column('allowed_resources', sa.JSON(), nullable=True),
        sa.Column('parent_agent_id', sa.String(length=255), nullable=True),
        sa.Column('delegation_depth', sa.Integer(), nullable=False),
        sa.Column('delegation_chain', sa.JSON(), nullable=False),
        sa.Column('owner_user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('owner_service_account_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('use_count', sa.Integer(), nullable=False),
        sa.Column('last_ip', sa.String(length=45), nullable=True),
        sa.Column('karma_score', sa.Integer(), nullable=False),
        sa.Column('successful_operations', sa.Integer(), nullable=False),
        sa.Column('failed_operations', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['owner_service_account_id'], ['service_accounts.id'], ),
        sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['parent_agent_id'], ['agent_credentials.agent_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_credentials_agent_id'), 'agent_credentials', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agent_credentials_expires_at'), 'agent_credentials', ['expires_at'], unique=False)
    op.create_index(op.f('ix_agent_credentials_parent_agent_id'), 'agent_credentials', ['parent_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_credentials_status'), 'agent_credentials', ['status'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop agent_credentials table
    op.drop_index(op.f('ix_agent_credentials_status'), table_name='agent_credentials')
    op.drop_index(op.f('ix_agent_credentials_parent_agent_id'), table_name='agent_credentials')
    op.drop_index(op.f('ix_agent_credentials_expires_at'), table_name='agent_credentials')
    op.drop_index(op.f('ix_agent_credentials_agent_id'), table_name='agent_credentials')
    op.drop_table('agent_credentials')
    
    # Drop service_accounts table
    op.drop_index(op.f('ix_service_accounts_status'), table_name='service_accounts')
    op.drop_index(op.f('ix_service_accounts_name'), table_name='service_accounts')
    op.drop_index(op.f('ix_service_accounts_client_id'), table_name='service_accounts')
    op.drop_table('service_accounts')
    
    # Drop refresh_tokens table
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_family'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_status'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    
    # ### end Alembic commands ###
