"""
BRAiN Minimal Backend v2 - With Database Support
"""
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
import asyncpg
import redis.asyncio as redis
import os
import time
from contextlib import asynccontextmanager

# Configuration from environment
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://brain:brain@dev-postgres:5432/brain_dev"
)
REDIS_URL = os.getenv(
    "REDIS_URL",
    "redis://dev-redis:6379/0"
)

# Global connection pools
db_pool: Optional[asyncpg.Pool] = None
redis_client: Optional[redis.Redis] = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup and shutdown events"""
    global db_pool, redis_client

    # Startup
    try:
        # PostgreSQL connection pool
        db_pool = await asyncpg.create_pool(
            DATABASE_URL,
            min_size=2,
            max_size=10,
            command_timeout=60
        )
        print("✅ PostgreSQL connection pool created")

        # Redis connection
        redis_client = await redis.from_url(
            REDIS_URL,
            encoding="utf-8",
            decode_responses=True
        )
        await redis_client.ping()
        print("✅ Redis connection established")

    except Exception as e:
        print(f"⚠️  Warning: Database connections failed: {e}")
        print("   Backend will run in degraded mode")

    yield

    # Shutdown
    if db_pool:
        await db_pool.close()
        print("🔌 PostgreSQL connection pool closed")

    if redis_client:
        await redis_client.close()
        print("🔌 Redis connection closed")


# FastAPI app
app = FastAPI(
    title="BRAiN Minimal API v2",
    version="0.2.0-minimal",
    description="Minimal backend with database support",
    lifespan=lifespan
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Models
class HealthResponse(BaseModel):
    status: str
    mode: str
    timestamp: float
    version: str


class DBHealthResponse(BaseModel):
    status: str
    postgres: dict
    redis: dict
    timestamp: float


# Routes
@app.get("/")
def root():
    """Root endpoint"""
    return {
        "message": "BRAiN Minimal Backend v2",
        "version": "0.2.0-minimal",
        "features": ["postgres", "redis"],
        "endpoints": {
            "health": "/api/health",
            "db_health": "/api/db/health"
        }
    }


@app.get("/api/health", response_model=HealthResponse)
def health():
    """Basic health check"""
    return HealthResponse(
        status="healthy",
        mode="minimal-v2",
        timestamp=time.time(),
        version="0.2.0"
    )


@app.get("/api/db/health", response_model=DBHealthResponse)
async def db_health():
    """Database health check"""
    postgres_status = {"connected": False, "error": None}
    redis_status = {"connected": False, "error": None}

    # Check PostgreSQL
    if db_pool:
        try:
            async with db_pool.acquire() as conn:
                result = await conn.fetchval("SELECT 1")
                postgres_status = {
                    "connected": True,
                    "result": result,
                    "pool_size": db_pool.get_size(),
                    "pool_free": db_pool.get_idle_size()
                }
        except Exception as e:
            postgres_status = {"connected": False, "error": str(e)}
    else:
        postgres_status = {"connected": False, "error": "Pool not initialized"}

    # Check Redis
    if redis_client:
        try:
            pong = await redis_client.ping()
            redis_status = {
                "connected": True,
                "ping": pong
            }
        except Exception as e:
            redis_status = {"connected": False, "error": str(e)}
    else:
        redis_status = {"connected": False, "error": "Client not initialized"}

    # Overall status
    overall_status = "healthy" if (
        postgres_status["connected"] and redis_status["connected"]
    ) else "degraded"

    return DBHealthResponse(
        status=overall_status,
        postgres=postgres_status,
        redis=redis_status,
        timestamp=time.time()
    )


@app.get("/docs")
def get_docs():
    """Redirect to API docs"""
    return {
        "message": "API documentation",
        "openapi": "/openapi.json",
        "swagger": "/docs (auto-generated by FastAPI)"
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
